services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./dockerfile
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    expose:
      - 8080

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./dockerfile
    restart: always
    ports:
      - "127.0.0.1:5173:5173"
    expose:
      - 5173
